smalltalk add "msc" "Hmmm. let's go ahead and profile it one more time."
smalltalk add "msc" "I'd say it's a zeropointeraccess... \n or maybe the hashtable is screwed up... or maybe..."
smalltalk add "msc" "We have another exception in the pipeline... \n the vertex buffer is ok though."
smalltalk add "msc" "I've been trying to find the bug for hours - \n in the end it turned out to be a \nwrong alignment in the struct!"
smalltalk add "msc" "No, it won't be relocated. Take the \n coordinates modulo to the Pos-Hash coordinates!"
smalltalk add "msc" "It's fundamentally trivial!"
smalltalk add "msc" "Let's check it out!"
smalltalk add "msc" "I know, let's use vertex colors!"
smalltalk add "msc" "I believe the small block heap is corrupted."
smalltalk add "msc" "You are not supposed to use self-modifying codes!"
smalltalk add "msc" "define private public ... which one of you guys did that?"
smalltalk add "msc" "I know a joke: two pointers meet on the heap. \n The first one says: 'I'm pointing at you!' \n The second one replies: 'Funny, I was going to say the same...'"
smalltalk add "msc" "CFluid takes away 25 percent of the performance... that's \n not good, not good at all..."
smalltalk add "msc" "Simply add kmem_heap_check!"

